version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8-jdk-8

    working_directory: ~/project

    steps:
      - checkout

      - run:
          - name: Build and Run Tests
            command: mvn test

          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v4.0.1
            with:
             token: ${{ secrets.CODECOV_TOKEN }}
             slug: MOINAHADIDJA/ceri-m1-techniques-de-test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
