version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8-jdk-8

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Build and Run Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
