version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/ceri-m1-techniques-de-test

    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test
      - run:
          name: Coverage to Codecov
          command: |
            echo 'export CODECOV_TOKEN=${CODECOV_TOKEN}' >> $BASH_ENV
            source $BASH_ENV
            bash <(curl -s https://codecov.io/bash)
      - run:
          name : Run checkStyle
          command : |
            wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.44/checkstyle-8.44-all.jar
            wget https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml
            java -jar checkstyle-8.44-all.jar -c google_checks.xml src/*

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master